name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check yarn cache integrity
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build packages
        run: yarn build
      # format tests don't pass on node 12 since icu is missing and tests don't work with locals
      - name: Test packages
        run: yarn test
      - name: Upload coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)
